apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mindspore-summary-new
resources:
- mindspore-summary-deployment.yaml
- mindspore-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
- sa.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: 602184701e2fcf43b14378416771efa55d792717
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/summary
  newTag: v1.0.20240109171013
