apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    topic: github-webhook-openeuler
    user_agent: github-webhook-openeuler
    kafka:
      address: "${KAFKA_ADDRESS}"
      version: 2.3.0
    hmac: "${HMAC}"
