apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret
spec:
  name: secret-hook-delivery
  keysMap:
    webhook-hmac:
      path: secrets/data/mindspore/robot-github
      key: webhook-hmac
    KAFKA_ADDRESS:
      path: secrets/data/mindspore/robot-github
      key: KAFKA_ADDRESS
    HMAC:
      path: secrets/data/mindspore/robot-github
      key: HMAC