apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - opengauss/openGauss-server
      - opengauss/openGauss-workbench
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      labels_for_merge:
      - opengauss-cla/yes
      - ci-pipeline-success
      needs_issues: true

    - repos:
      - zengchen1024/repo-test
      - opengauss
      excluded_repos:
      - opengauss/tc
      - opengauss/openGauss-server
      - opengauss/docs
      - opengauss/openGauss-workbench
      - opengauss/openGauss-tools-sql-translator
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      labels_for_merge:
      - opengauss-cla/yes

    - repos:
      - opengauss/docs
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      labels_for_merge:
      - opengauss-cla/yes
      - ci-pipeline-success
      needs_issues: true

    - repos:
      - opengauss/tc
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      check_permission_based_on_sig_owners: true
      sigs_dir: sigs
      labels_for_merge:
      - opengauss-cla/yes

    - repos:
        - opengauss/openGauss-OM
        - opengauss/openGauss-connector-jdbc
        - opengauss/openGauss-connector-odbc
        - opengauss/CM
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      labels_for_merge:
        - opengauss-cla/yes
      missing_labels_for_merge:
        - codecheck-failed
      needs_issues: true
        
    - repos:
      - opengauss/openGauss-tools-sql-translator
      lgtm_counts_required: 2
      legal_operator: opengauss_bot
      labels_for_merge:
      - opengauss-cla/yes
      - codecheck-success
      needs_issues: true
    
    - repos:
      - opengauss/openGauss-third_party
      - opengauss/Plugin
      - opengauss/openGauss-DBMind
      - opengauss/openGauss-connector-python-pyog
      - opengauss/openGauss-connector-python-psycopg2
      - opengauss/openGauss-connector-go-pq
      - opengauss/CM-RestAPI
      - opengauss/CBB
      - opengauss/DSS
      - opengauss/DMS
      - opengauss/DCF
      - opengauss/DCC
      - opengauss/compatibility-assessment
      - opengauss/openGauss-tools-datachecker-performance
      - opengauss/debezium
      - opengauss/openGauss-migration-portal
      - opengauss/openGauss-tools-chameleon
      - opengauss/ora-migration-tool
      - opengauss/openGauss-container
      needs_issues: true
     
