apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updating-mindspore-sigs
  namespace: mindspore-meetingserver
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          serviceAccountName: mindspore-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server:master-305626
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              - name: MYSQL_TLS_PEM_PATH
                value: /vault/secrets/ca.pem
              - name: TLS_CRT_PATH
                value: /vault/secrets/server.crt
              - name: TLS_KEY_PATH
                value: /vault/secrets/server.key
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py genegroup

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-activity-status
  namespace: mindspore-meetingserver
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          serviceAccountName: mindspore-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server:master-305626
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              - name: MYSQL_TLS_PEM_PATH
                value: /vault/secrets/ca.pem
              - name: TLS_CRT_PATH
                value: /vault/secrets/server.crt
              - name: TLS_KEY_PATH
                value: /vault/secrets/server.key
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py update_activity_status

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-privacy-policy-cronjob
  namespace: mindspore-meetingserver
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          serviceAccountName: mindspore-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: Never
          containers:
          - name: meeting-server
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server:master-305626
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            - name: MYSQL_TLS_PEM_PATH
              value: /vault/secrets/ca.pem
            - name: TLS_CRT_PATH
              value: /vault/secrets/server.crt
            - name: TLS_KEY_PATH
              value: /vault/secrets/server.key
            command:
              - /bin/sh
              - -c
              - |
                python manage.py check_privacy_policy_update

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sendmessage-cronjob
  namespace: mindspore-meetingserver
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          serviceAccountName: mindspore-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: Never
          containers:
          - name: meeting-server
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server:master-305626
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            - name: MYSQL_TLS_PEM_PATH
              value: /vault/secrets/ca.pem
            - name: TLS_CRT_PATH
              value: /vault/secrets/server.crt
            - name: TLS_KEY_PATH
              value: /vault/secrets/server.key
            command:
              - /bin/sh
              - -c
              - |
                python manage.py sendmessages

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-logoff-user-cronjob
  namespace: mindspore-meetingserver
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"
            vault.hashicorp.com/agent-inject-perms-ca.pem: "0400"
            vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
            vault.hashicorp.com/agent-inject-perms-server.key: "0400"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.config }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-ca.pem: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-ca.pem: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.MysqlCA }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.crt: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.servercrt }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/mindspore/mindspore-meeting-v2'
            vault.hashicorp.com/agent-inject-template-server.key: |  
              {{- with secret "internal/data/mindspore/mindspore-meeting-v2" -}}  
              {{ .Data.data.serverkey }}
              {{- end }}
        spec:
          serviceAccountName: mindspore-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: Never
          containers:
          - name: meeting-server
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-meeting-server:master-305626
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            - name: MYSQL_TLS_PEM_PATH
              value: /vault/secrets/ca.pem
            - name: TLS_CRT_PATH
              value: /vault/secrets/server.crt
            - name: TLS_KEY_PATH
              value: /vault/secrets/server.key
            command:
              - /bin/sh
              - -c
              - |
                python manage.py clean_logoff_user